Added unit tests
abuzaforfagun/Invoice.Microservices.ThirdPartyAPIIntegration pull request #17
Opened 2021-09-27 07:24 UTC by ysnarafat

Add unit tests for issue #8

2021-10-10 07:55 UTC, abuzaforfagun requested changes

2021-10-10 07:55 UTC, abuzaforfagun commented on InvoiceProcessor.Application/Queries/Outbox/GetPendingProcess/QueryHandler.cs
> +                    guid: x.Guid.GetValueOrDefault(),
What's the reason behind this modification?

2021-10-10 07:55 UTC, abuzaforfagun commented on InvoiceProcessor.Tests/Application/Queries/Outbox/GetPendingProcessTests.cs
> +            _outboxStorageMock.Setup(x => x.GetPendingItemsAsync(new CancellationToken()))
We need to do the setup the mock before using the mock.

2021-10-10 07:55 UTC, abuzaforfagun commented on InvoiceProcessor.Tests/Application/Queries/Outbox/GetPendingProcessTests.cs
> +            List<Model> models = null;
When there is no pending invoice, it returns an empty List not null. And when you want to pass null, you directly can pass null insisted of creating another variable.

2021-10-10 07:55 UTC, abuzaforfagun commented on InvoiceProcessor.Tests/Application/Queries/Outbox/GetPendingProcessTests.cs
> +            Assert.NotStrictEqual(models, results);
I think the assertion is not working correctly, when you remove one item from models variable, it still pass.

2021-10-10 07:55 UTC, abuzaforfagun commented on InvoiceProcessor.Tests/Application/Queries/Outbox/GetProcessStatusTests.cs
> +            _processStatusRepositoryMock.Setup(x => x.GetProcessStatus(message))
When setting up mock for generic values, it's better to use It.IsAny<Type>()

2021-10-10 07:55 UTC, abuzaforfagun commented on InvoiceProcessor.Tests/Infrastructure/Outbox/Services/OutBoxServiceTests.cs
> +            _storageMock.Verify();
What it would verify?

2021-10-11 17:35 UTC, ysnarafat commented on InvoiceProcessor.Application/Queries/Outbox/GetPendingProcess/QueryHandler.cs
> +                    guid: x.Guid.GetValueOrDefault(),
Previously OutboxItem Guid property was nullable. At that time it was throwing exception while accessing nullable value.

2021-10-13 18:09 UTC, abuzaforfagun approved these changes

2021-10-13 18:09 UTC, merged